/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PublicRouteImport } from './routes/public'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicIndexRouteImport } from './routes/public.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as PublicTrendsRouteImport } from './routes/public.trends'
import { Route as PublicSafetyRouteImport } from './routes/public.safety'
import { Route as PublicReportRouteImport } from './routes/public.report'
import { Route as PublicHeatmapRouteImport } from './routes/public.heatmap'
import { Route as PublicEmergencyRouteImport } from './routes/public.emergency'
import { Route as PublicAlertsRouteImport } from './routes/public.alerts'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppResourcesRouteImport } from './routes/app.resources'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppPredictionsRouteImport } from './routes/app.predictions'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppNetworkRouteImport } from './routes/app.network'
import { Route as AppMapRouteImport } from './routes/app.map'
import { Route as AppDistrictsRouteImport } from './routes/app.districts'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppAssistantRouteImport } from './routes/app.assistant'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAlertsRouteImport } from './routes/app.alerts'

const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/public',
  path: '/public',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const PublicTrendsRoute = PublicTrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSafetyRoute = PublicSafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => PublicRoute,
} as any)
const PublicReportRoute = PublicReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => PublicRoute,
} as any)
const PublicHeatmapRoute = PublicHeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => PublicRoute,
} as any)
const PublicEmergencyRoute = PublicEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAlertsRoute = PublicAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => PublicRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppResourcesRoute = AppResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPredictionsRoute = AppPredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppNetworkRoute = AppNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AppRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRoute,
} as any)
const AppDistrictsRoute = AppDistrictsRouteImport.update({
  id: '/districts',
  path: '/districts',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/public': typeof PublicRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/districts': typeof AppDistrictsRoute
  '/app/map': typeof AppMapRoute
  '/app/network': typeof AppNetworkRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/predictions': typeof AppPredictionsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/resources': typeof AppResourcesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/users': typeof AppUsersRoute
  '/public/alerts': typeof PublicAlertsRoute
  '/public/emergency': typeof PublicEmergencyRoute
  '/public/heatmap': typeof PublicHeatmapRoute
  '/public/report': typeof PublicReportRoute
  '/public/safety': typeof PublicSafetyRoute
  '/public/trends': typeof PublicTrendsRoute
  '/app/': typeof AppIndexRoute
  '/public/': typeof PublicIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/districts': typeof AppDistrictsRoute
  '/app/map': typeof AppMapRoute
  '/app/network': typeof AppNetworkRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/predictions': typeof AppPredictionsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/resources': typeof AppResourcesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/users': typeof AppUsersRoute
  '/public/alerts': typeof PublicAlertsRoute
  '/public/emergency': typeof PublicEmergencyRoute
  '/public/heatmap': typeof PublicHeatmapRoute
  '/public/report': typeof PublicReportRoute
  '/public/safety': typeof PublicSafetyRoute
  '/public/trends': typeof PublicTrendsRoute
  '/app': typeof AppIndexRoute
  '/public': typeof PublicIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/public': typeof PublicRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/districts': typeof AppDistrictsRoute
  '/app/map': typeof AppMapRoute
  '/app/network': typeof AppNetworkRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/predictions': typeof AppPredictionsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/resources': typeof AppResourcesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/users': typeof AppUsersRoute
  '/public/alerts': typeof PublicAlertsRoute
  '/public/emergency': typeof PublicEmergencyRoute
  '/public/heatmap': typeof PublicHeatmapRoute
  '/public/report': typeof PublicReportRoute
  '/public/safety': typeof PublicSafetyRoute
  '/public/trends': typeof PublicTrendsRoute
  '/app/': typeof AppIndexRoute
  '/public/': typeof PublicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/public'
    | '/reset-password'
    | '/sitemap.xml'
    | '/verify-otp'
    | '/app/alerts'
    | '/app/analytics'
    | '/app/assistant'
    | '/app/dashboard'
    | '/app/districts'
    | '/app/map'
    | '/app/network'
    | '/app/notifications'
    | '/app/predictions'
    | '/app/reports'
    | '/app/resources'
    | '/app/settings'
    | '/app/users'
    | '/public/alerts'
    | '/public/emergency'
    | '/public/heatmap'
    | '/public/report'
    | '/public/safety'
    | '/public/trends'
    | '/app/'
    | '/public/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/sitemap.xml'
    | '/verify-otp'
    | '/app/alerts'
    | '/app/analytics'
    | '/app/assistant'
    | '/app/dashboard'
    | '/app/districts'
    | '/app/map'
    | '/app/network'
    | '/app/notifications'
    | '/app/predictions'
    | '/app/reports'
    | '/app/resources'
    | '/app/settings'
    | '/app/users'
    | '/public/alerts'
    | '/public/emergency'
    | '/public/heatmap'
    | '/public/report'
    | '/public/safety'
    | '/public/trends'
    | '/app'
    | '/public'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/public'
    | '/reset-password'
    | '/sitemap.xml'
    | '/verify-otp'
    | '/app/alerts'
    | '/app/analytics'
    | '/app/assistant'
    | '/app/dashboard'
    | '/app/districts'
    | '/app/map'
    | '/app/network'
    | '/app/notifications'
    | '/app/predictions'
    | '/app/reports'
    | '/app/resources'
    | '/app/settings'
    | '/app/users'
    | '/public/alerts'
    | '/public/emergency'
    | '/public/heatmap'
    | '/public/report'
    | '/public/safety'
    | '/public/trends'
    | '/app/'
    | '/public/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  PublicRoute: typeof PublicRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public': {
      id: '/public'
      path: '/public'
      fullPath: '/public'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/': {
      id: '/public/'
      path: '/'
      fullPath: '/public/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/public/trends': {
      id: '/public/trends'
      path: '/trends'
      fullPath: '/public/trends'
      preLoaderRoute: typeof PublicTrendsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/public/safety': {
      id: '/public/safety'
      path: '/safety'
      fullPath: '/public/safety'
      preLoaderRoute: typeof PublicSafetyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/public/report': {
      id: '/public/report'
      path: '/report'
      fullPath: '/public/report'
      preLoaderRoute: typeof PublicReportRouteImport
      parentRoute: typeof PublicRoute
    }
    '/public/heatmap': {
      id: '/public/heatmap'
      path: '/heatmap'
      fullPath: '/public/heatmap'
      preLoaderRoute: typeof PublicHeatmapRouteImport
      parentRoute: typeof PublicRoute
    }
    '/public/emergency': {
      id: '/public/emergency'
      path: '/emergency'
      fullPath: '/public/emergency'
      preLoaderRoute: typeof PublicEmergencyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/public/alerts': {
      id: '/public/alerts'
      path: '/alerts'
      fullPath: '/public/alerts'
      preLoaderRoute: typeof PublicAlertsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/resources': {
      id: '/app/resources'
      path: '/resources'
      fullPath: '/app/resources'
      preLoaderRoute: typeof AppResourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/predictions': {
      id: '/app/predictions'
      path: '/predictions'
      fullPath: '/app/predictions'
      preLoaderRoute: typeof AppPredictionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/network': {
      id: '/app/network'
      path: '/network'
      fullPath: '/app/network'
      preLoaderRoute: typeof AppNetworkRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/map': {
      id: '/app/map'
      path: '/map'
      fullPath: '/app/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/districts': {
      id: '/app/districts'
      path: '/districts'
      fullPath: '/app/districts'
      preLoaderRoute: typeof AppDistrictsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assistant': {
      id: '/app/assistant'
      path: '/assistant'
      fullPath: '/app/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAssistantRoute: typeof AppAssistantRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDistrictsRoute: typeof AppDistrictsRoute
  AppMapRoute: typeof AppMapRoute
  AppNetworkRoute: typeof AppNetworkRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPredictionsRoute: typeof AppPredictionsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppResourcesRoute: typeof AppResourcesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAssistantRoute: AppAssistantRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDistrictsRoute: AppDistrictsRoute,
  AppMapRoute: AppMapRoute,
  AppNetworkRoute: AppNetworkRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPredictionsRoute: AppPredictionsRoute,
  AppReportsRoute: AppReportsRoute,
  AppResourcesRoute: AppResourcesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PublicRouteChildren {
  PublicAlertsRoute: typeof PublicAlertsRoute
  PublicEmergencyRoute: typeof PublicEmergencyRoute
  PublicHeatmapRoute: typeof PublicHeatmapRoute
  PublicReportRoute: typeof PublicReportRoute
  PublicSafetyRoute: typeof PublicSafetyRoute
  PublicTrendsRoute: typeof PublicTrendsRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAlertsRoute: PublicAlertsRoute,
  PublicEmergencyRoute: PublicEmergencyRoute,
  PublicHeatmapRoute: PublicHeatmapRoute,
  PublicReportRoute: PublicReportRoute,
  PublicSafetyRoute: PublicSafetyRoute,
  PublicTrendsRoute: PublicTrendsRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  PublicRoute: PublicRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VerifyOtpRoute: VerifyOtpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
